# Python Version

PYTHON_VERSION = '2.7.10'

# time constants

SECONDS = 1
MINUTES = 60 * SECONDS
HOURS = 60*MINUTES

# Preprocessor
PREPROCESS_SLEEP_TIME = 10*MINUTES

# Extractor
MAX_TWEETS_IN_FILE = 10000
DISPLAY_COMPLETED_TWEETS_INTERVAL = 1000

FILE_NUMBER_RESET_VALUE = 100
FILE_NAME_SUFFIX_DIGITS = 2

# Manager Process
STOP_DATA_EXTRACTION_TIME = '23:55'
RESTART_DATA_EXTRACTION_TIME = '00:05'
